config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/dashboard'
  get 'pages/create'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :start, presence: true
    validates :end, presence: true
    validates :state, presence: true
    scope :find_valid, -> { where("state > ?", :state) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
  def index
  end

  def dashboard
    if params[:state].present?
      @project = Project.where('state Like ?', params[:state])
    else 
      @project = Project.all
    end
  end

  def create
    @project = Project.create(name: params[:name], description: params[:description], start: params[:start], end: params[:end], state: params[:state])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container max-with">
       <%= yield %>
    </div>
  </body>
</html>

app/views/pages/create.html.erb
<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@project.errors.count, "error") %> 
            prohibited thisarticle from being saved:
        </h2>
        <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% else %>
    <h1> Te registraste con exito </h1>
<% end %>

app/views/pages/dashboard.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">Navbar</a>
    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="state">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</nav>


<table class="table">
    <tr>
        <th>Nombre Projecto</th>
        <th>Descripcion</th>
        <th>Fecha inicio</th>
        <th>Fecha termino</th>
        <th>Estado</th>
    </tr>

    <% @project.each do |project| %>
        <tr>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= project.start %></td>
            <td><%= project.end %></td>
            <td><%= project.state %></td>
        </tr>
    <% end %>
</table>

app/views/pages/index.html.erb
<h1>Ingrese proyecto</h1>
<form method="get" action=" <%= pages_create_path %> ">
   <div class="form-group">
   <label for="name">Nombre proyecto</label>
    <input name="name" class="form-control" placeholder="Ingresar nombre proyecto">
    </div>

    <div class="form-group">
        <label for="description">Descripción</label> 
        <textarea name="description" class="form-control" placeholder="Ingresar descripcion del proyecto"></textarea>
    </div>

    <div class="form-group">
        <label for="start">Start date:</label>
        <input type="date" id="start" name="start" min="1900-01-01" max="2099-12-31">
    </div>

    <div class="form-group">
        <label for="end">End date :</label>
        <input type="date" id="start" name="end" min="1900-01-01" max="2099-12-31">
    </div>

    <%= form_tag("/search", method: "get") do %>
        <label for="state">Estado</label>
        <select class="form-control" id="state" name="state">
            <option>Propuesta</option>
            <option>En progreso</option>
            <option>Terminado</option>
        </select> 
        <br>
        <button type="submit" class="btn btn-primary">Enviar</button>
    <% end %>
</form>